alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: web
      match:
        authority:
          exact: ""
        path:
          prefix: /
    - component:
        name: playwright-server
      match:
        authority:
          exact: ""
        path:
          prefix: /playwright-server
    - component:
        name: playwright-mcp
      match:
        authority:
          exact: ""
        path:
          prefix: /playwright-mcp
name: apps-gradient-cua-demo
region: nyc
services:
  - environment_slug: node-js
    envs:
      - key: NEXT_PUBLIC_BASE_URL
        scope: RUN_TIME
        value: https://apps-gradient-cua-demo-6jkgj.ondigitalocean.app
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: your_model_key_here
      - key: GRADIENT_BASE_URL
        scope: RUN_TIME
        value: https://inference.do-ai.run/v1
      - key: DO_SPACES_ENDPOINT
        scope: RUN_TIME
        value: https://nyc3.digitaloceanspaces.com
      - key: DO_SPACES_REGION
        scope: RUN_TIME
        value: nyc3
      - key: DO_SPACES_ACCESS_KEY
        scope: RUN_TIME
        value: your_access_key_here
      - key: DO_SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: your_secret_key_here
      - key: DO_SPACES_BUCKET
        scope: RUN_TIME
        value: your_bucket_name_here
      - key: PLAYWRIGHT_SERVER_ENDPOINT
        scope: RUN_TIME
        value: http://playwright-server:8081
      - key: PLAYWRIGHT_MCP_ENDPOINT
        scope: RUN_TIME
        value: http://playwright-mcp:8080/mcp
    github:
      branch: main
      deploy_on_push: true
      repo: digitalocean/template-app-platform-gradient-cua-chat
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-d-2vcpu-8gb
    name: web
    run_command: yarn start
    source_dir: /
  - dockerfile_path: Dockerfile.mcp
    envs:
      - key: PLAYWRIGHT_MCP_VERSION
        scope: BUILD_TIME
        value: 0.0.32
    github:
      branch: main
      deploy_on_push: true
      repo: digitalocean/template-app-platform-gradient-cua-chat
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-d-2vcpu-8gb
    name: playwright-mcp
  - dockerfile_path: Dockerfile.playwright
    envs:
      - key: PLAYWRIGHT_VERSION
        scope: BUILD_TIME
        value: 1.54.1
    github:
      branch: main
      deploy_on_push: true
      repo: digitalocean/template-app-platform-gradient-cua-chat
    http_port: 8081
    instance_count: 1
    instance_size_slug: apps-d-2vcpu-8gb
    name: playwright-server
